max_position_weight: 0.06
min_position_weight: 0.01
trim_over: 1.20
add_under: 0.80

buy_score_min: 70
add_score_min: 60
avoid_score_max: 45

buy_upside_min: 0.07
add_upside_min: 0.03

always_hold:
  - V
  - TSLA
  - LLY
